import { StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: 'column',
    backgroundColor: '#F5F5F5',
    padding: 20,
  },
  text: {
    color: 'green',
    fontSize: 50,
    fontWeight: 'bold',
    textAlign: 'center',
    marginVertical: 20,
  },
  singup: {
    color: 'black',
    fontSize: 35,
    fontWeight: 'bold',
    textAlign: 'center',
    marginTop: 10,
    marginBottom: 60,
  },
  info: {
    color: 'black',
    fontSize: 15,
    fontWeight: 'bold',
    marginVertical: 5,
  },
  input: {
    height: 40,
    paddingVertical: 10,
    borderColor: 'gray',
    borderWidth: 1,
    borderRadius: 5,
    paddingHorizontal: 10,
    marginBottom: 10,
    backgroundColor: 'white',
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    textAlign: 'center',
    marginVertical: 10,
  },
  buttonContainer: {
    width: '10%', // Adjusted width to center the button
    backgroundColor: '#FF0000',
    borderRadius: 20,
    alignSelf: 'center', 
  },
  buttonText: {
    color: '#FFFFFF',
    textAlign: 'center',
    padding: 10,
    fontWeight: 'bold',
  },
  centerContent: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  waveContainer: {
    position: 'absolute',
    bottom: 0,
    width: '100%',
  },
  wave: {
    height: 100,
    backgroundColor: '#e60000',
    borderTopLeftRadius: 100,
    borderTopRightRadius: 100,
  },
  waveLight: {
    height: 80,
    backgroundColor: '#ff4d4d',
    borderTopLeftRadius: 100,
    borderTopRightRadius: 100,
    marginTop: -40,
  },
  searchInput: {
    position: 'relative',
    left: 100,
    width: '20%',
    height: 100,
    borderColor: '#2590df',
    fontSize: 20,
    borderWidth: 1,
    borderRadius: 50,
    paddingHorizontal: 20,
    paddingVertical: 10,
    marginBottom: 20,
    backgroundColor: '#F0F0F0',
  },
  searchInputFocused: {
    width: '50%',
    borderColor: '#2590df',
    backgroundColor: '#F0F0F0',
  },
});
